// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: reverse.proto

package revers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestReverse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RequestReverse) Reset() {
	*x = RequestReverse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reverse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestReverse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReverse) ProtoMessage() {}

func (x *RequestReverse) ProtoReflect() protoreflect.Message {
	mi := &file_reverse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReverse.ProtoReflect.Descriptor instead.
func (*RequestReverse) Descriptor() ([]byte, []int) {
	return file_reverse_proto_rawDescGZIP(), []int{0}
}

func (x *RequestReverse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResponseReverse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseReverse) Reset() {
	*x = ResponseReverse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reverse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReverse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReverse) ProtoMessage() {}

func (x *ResponseReverse) ProtoReflect() protoreflect.Message {
	mi := &file_reverse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReverse.ProtoReflect.Descriptor instead.
func (*ResponseReverse) Descriptor() ([]byte, []int) {
	return file_reverse_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseReverse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_reverse_proto protoreflect.FileDescriptor

var file_reverse_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x53, 0x61, 0x6e, 0x65, 0x34, 0x65, 0x6b, 0x35, 0x35, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x62, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x02,
	0x44, 0x6f, 0x12, 0x27, 0x2e, 0x53, 0x61, 0x6e, 0x65, 0x34, 0x65, 0x6b, 0x35, 0x35, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x1a, 0x28, 0x2e, 0x53, 0x61,
	0x6e, 0x65, 0x34, 0x65, 0x6b, 0x35, 0x35, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x3b, 0x72, 0x65, 0x76, 0x65, 0x72,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reverse_proto_rawDescOnce sync.Once
	file_reverse_proto_rawDescData = file_reverse_proto_rawDesc
)

func file_reverse_proto_rawDescGZIP() []byte {
	file_reverse_proto_rawDescOnce.Do(func() {
		file_reverse_proto_rawDescData = protoimpl.X.CompressGZIP(file_reverse_proto_rawDescData)
	})
	return file_reverse_proto_rawDescData
}

var file_reverse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reverse_proto_goTypes = []interface{}{
	(*RequestReverse)(nil),  // 0: Sane4ek55.grpc_test.api.RequestReverse
	(*ResponseReverse)(nil), // 1: Sane4ek55.grpc_test.api.ResponseReverse
}
var file_reverse_proto_depIdxs = []int32{
	0, // 0: Sane4ek55.grpc_test.api.Reverse.Do:input_type -> Sane4ek55.grpc_test.api.RequestReverse
	1, // 1: Sane4ek55.grpc_test.api.Reverse.Do:output_type -> Sane4ek55.grpc_test.api.ResponseReverse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reverse_proto_init() }
func file_reverse_proto_init() {
	if File_reverse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reverse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestReverse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reverse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReverse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reverse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reverse_proto_goTypes,
		DependencyIndexes: file_reverse_proto_depIdxs,
		MessageInfos:      file_reverse_proto_msgTypes,
	}.Build()
	File_reverse_proto = out.File
	file_reverse_proto_rawDesc = nil
	file_reverse_proto_goTypes = nil
	file_reverse_proto_depIdxs = nil
}
